-- Our Space chat reliability + push notification setup
-- Run this whole file once in Supabase SQL Editor.

-- ============================================================
-- PUSH SUBSCRIPTIONS
-- ============================================================

create table if not exists public.push_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  endpoint text not null unique,
  subscription jsonb not null,
  preview_enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.push_subscriptions enable row level security;

drop policy if exists "Users can read own push subscriptions"
on public.push_subscriptions;
create policy "Users can read own push subscriptions"
on public.push_subscriptions for select to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users can create own push subscriptions"
on public.push_subscriptions;
create policy "Users can create own push subscriptions"
on public.push_subscriptions for insert to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users can update own push subscriptions"
on public.push_subscriptions;
create policy "Users can update own push subscriptions"
on public.push_subscriptions for update to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users can delete own push subscriptions"
on public.push_subscriptions;
create policy "Users can delete own push subscriptions"
on public.push_subscriptions for delete to authenticated
using (auth.uid() = user_id);

create index if not exists push_subscriptions_user_id_idx
on public.push_subscriptions(user_id);

create or replace function public.touch_push_subscription()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists push_subscriptions_touch
on public.push_subscriptions;

create trigger push_subscriptions_touch
before update on public.push_subscriptions
for each row execute function public.touch_push_subscription();

-- ============================================================
-- MESSAGE COLUMNS
-- ============================================================

alter table public.messages
  add column if not exists seen_at timestamptz,
  add column if not exists deleted_at timestamptz,
  add column if not exists deleted_by uuid references auth.users(id);

-- ============================================================
-- REALTIME
-- ============================================================

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'messages'
  ) then
    execute 'alter publication supabase_realtime add table public.messages';
  end if;
end
$$;

alter table public.messages replica identity full;

-- Realtime Postgres Changes authorizes subscribers through SELECT RLS.
-- Both members of the space must be able to read message rows.
grant select on public.messages to authenticated;

drop policy if exists "Our Space members can read messages"
on public.messages;

create policy "Our Space members can read messages"
on public.messages
for select
to authenticated
using (
  exists (
    select 1
    from public.space_members sm
    where sm.space_id = messages.space_id
      and sm.user_id = auth.uid()
  )
);

-- Sending messages remains restricted to a member sending as themselves.
grant insert on public.messages to authenticated;

drop policy if exists "Our Space members can send messages"
on public.messages;

create policy "Our Space members can send messages"
on public.messages
for insert
to authenticated
with check (
  sender_id = auth.uid()
  and exists (
    select 1
    from public.space_members sm
    where sm.space_id = messages.space_id
      and sm.user_id = auth.uid()
  )
);

-- ============================================================
-- SEEN
-- ============================================================

drop function if exists public.mark_message_seen(bigint);

create or replace function public.mark_message_seen(
  p_message_id bigint
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  changed boolean := false;
begin
  update public.messages m
  set seen_at = coalesce(m.seen_at, now())
  where m.id = p_message_id
    and m.sender_id <> auth.uid()
    and exists (
      select 1
      from public.space_members sm
      where sm.space_id = m.space_id
        and sm.user_id = auth.uid()
    );

  changed := found;
  return changed;
end;
$$;

revoke all on function public.mark_message_seen(bigint) from public;
grant execute on function public.mark_message_seen(bigint) to authenticated;

-- ============================================================
-- DELETE FOR EVERYONE
-- ============================================================

drop function if exists public.delete_message_for_everyone(bigint);

create or replace function public.delete_message_for_everyone(
  p_message_id bigint
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  changed boolean := false;
begin
  update public.messages m
  set
    deleted_at = coalesce(m.deleted_at, now()),
    deleted_by = auth.uid()
  where m.id = p_message_id
    and m.sender_id = auth.uid()
    and m.deleted_at is null;

  changed := found;
  return changed;
end;
$$;

revoke all on function public.delete_message_for_everyone(bigint) from public;
grant execute on function public.delete_message_for_everyone(bigint) to authenticated;
