-- Our Space push notification setup
-- Run this once in Supabase SQL Editor.

create table if not exists public.push_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  endpoint text not null unique,
  subscription jsonb not null,
  preview_enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.push_subscriptions enable row level security;

drop policy if exists "Users can read own push subscriptions"
on public.push_subscriptions;

create policy "Users can read own push subscriptions"
on public.push_subscriptions
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users can create own push subscriptions"
on public.push_subscriptions;

create policy "Users can create own push subscriptions"
on public.push_subscriptions
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users can update own push subscriptions"
on public.push_subscriptions;

create policy "Users can update own push subscriptions"
on public.push_subscriptions
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users can delete own push subscriptions"
on public.push_subscriptions;

create policy "Users can delete own push subscriptions"
on public.push_subscriptions
for delete
to authenticated
using (auth.uid() = user_id);

create index if not exists push_subscriptions_user_id_idx
on public.push_subscriptions(user_id);

create or replace function public.touch_push_subscription()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists push_subscriptions_touch
on public.push_subscriptions;

create trigger push_subscriptions_touch
before update on public.push_subscriptions
for each row execute function public.touch_push_subscription();


-- Chat realtime + secure seen-status updates
-- Run this in Supabase SQL Editor as well.

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'messages'
  ) then
    execute 'alter publication supabase_realtime add table public.messages';
  end if;
end
$$;

alter table public.messages replica identity full;

create or replace function public.mark_message_seen(p_message_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.messages m
  set seen_at = coalesce(m.seen_at, now())
  where m.id = p_message_id
    and m.sender_id <> auth.uid()
    and exists (
      select 1
      from public.space_members sm
      where sm.space_id = m.space_id
        and sm.user_id = auth.uid()
    );
end;
$$;

revoke all on function public.mark_message_seen(bigint) from public;
grant execute on function public.mark_message_seen(bigint) to authenticated;


create or replace function public.delete_message_for_everyone(p_message_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.messages m
  set deleted_at = coalesce(m.deleted_at, now()),
      deleted_by = auth.uid()
  where m.id = p_message_id
    and m.sender_id = auth.uid()
    and m.deleted_at is null;
end;
$$;
revoke all on function public.delete_message_for_everyone(bigint) from public;
grant execute on function public.delete_message_for_everyone(bigint) to authenticated;
